using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;
using System.Diagnostics;
using Microsoft.Office.Interop.Excel;
using DataTable = System.Data.DataTable;

namespace BusinessContacts
{
    public partial class BizContacts : Form
    {
        string connString = @"Data Source=LAPTOP-TN4226FN\SQLEXPRESS;Initial Catalog=AddressBook;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";
        SqlDataAdapter dataAdapter;
        DataTable table;
        SqlCommandBuilder commandBuilder;
        SqlConnection conn;
        string selectionStatement = "Select * from BizContacts";


        public BizContacts()
        {
            InitializeComponent();
        }

        private void Label8_Click(object sender, EventArgs e)
        {
        }

        private void BizContacts_Load(object sender, EventArgs e)
        {
            comboBox1.SelectedIndex = 0;
            dataGridView1.DataSource = bindingSource1;
            //dataGridView1.DataSource = table;
            GetData("Select * from BizContacts;"); // tells the adapter which table to look for data source
            
        }

        // updates the bindingSource with a new table generated by sql
        private void GetData(string sql)
        {
            try
            {
                dataAdapter = new SqlDataAdapter(sql, connString);
                table = new DataTable();
                table.Locale = System.Globalization.CultureInfo.InvariantCulture;
                dataAdapter.Fill(table);

                bindingSource1.DataSource = table;
                dataGridView1.Columns[0].ReadOnly = true; // disables edits to the ID field
            } catch(SqlException ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void Button4_Click(object sender, EventArgs e)
        {
            SqlCommand command;
            string insert = @"insert into BizContacts(Date_Added, Company, Website, Title, First_Name, Last_Name, Address, 
                                            City, State, Postal_Code, Mobile, Notes)
                            values(@Date_Added, @Company, @Website, @Title, @First_Name, @Last_Name, @Address, 
                                        @City, @State, @Postal_Code, @Mobile, @Notes)";
            //string insert = @"insert into BizContacts(Date_Added, Company)
                           // values(@Date_Added, @Company)";
            using (conn = new SqlConnection(connString))
            {
                conn.Open();
                command = new SqlCommand(insert, conn);
                command.Parameters.AddWithValue(@"Date_Added", dateTimePicker1.Value.Date);
                command.Parameters.AddWithValue(@"Company", txtCompany.Text);
                command.Parameters.AddWithValue(@"Website", txtWebsite.Text);
                command.Parameters.AddWithValue(@"Title", txtTitle.Text);
                command.Parameters.AddWithValue(@"First_Name", txtFN.Text);
                command.Parameters.AddWithValue(@"Last_Name", txtLN.Text);
                command.Parameters.AddWithValue(@"Address", txtAddress.Text);
                command.Parameters.AddWithValue(@"City", txtCity.Text);
                command.Parameters.AddWithValue(@"State", txtState.Text);
                command.Parameters.AddWithValue(@"Postal_Code", txtPC.Text);
                command.Parameters.AddWithValue(@"Mobile", txtMobile.Text);
                command.Parameters.AddWithValue(@"Notes", txtNotes.Text);
                command.ExecuteNonQuery();
            }
            GetData("Select * from BizContacts");
            dataGridView1.Update();
        }

        private void DataGridView1_CellEndEdit(object sender, DataGridViewCellEventArgs e)
        {
            commandBuilder = new SqlCommandBuilder(dataAdapter);
            dataAdapter.UpdateCommand = commandBuilder.GetUpdateCommand();
            try
            {
                bindingSource1.EndEdit();
                dataAdapter.Update(table);
            }
            catch (Exception ex)
            {

            }
        }

        private void Button3_Click(object sender, EventArgs e)
        {
            DataGridViewRow row = dataGridView1.CurrentCell.OwningRow;
            string value = row.Cells["ID"].Value.ToString();
            string fname = row.Cells["First_Name"].Value.ToString();
            string lname = row.Cells["Last_Name"].Value.ToString();
            DialogResult result = MessageBox.Show("Do you want to del" + fname + " " + lname + ", record "+value, 
                "Message", MessageBoxButtons.YesNo, MessageBoxIcon.Question);

            string deleteSql = @"delete from BizContacts where ID = '" + value + "'";

            if (result == DialogResult.Yes)
            {
                using (conn = new SqlConnection(connString))
                {
                    try
                    {
                        conn.Open();
                        SqlCommand comm = new SqlCommand(deleteSql, conn);
                        comm.ExecuteNonQuery();
                        GetData(selectionStatement);
                        dataGridView1.Update();
                    } catch (Exception ex)
                    {

                    }
                }
            }

            

        }

        private void Button1_Click(object sender, EventArgs e)
        {
            switch (comboBox1.SelectedItem.ToString())
            {
                case "First Name":
                    GetData("select * from BizContacts where lower(first_name) like '%" + txtSearch.Text.ToLower() + "%'");
                    break;
                case "Last Name":
                    GetData("select * from BizContacts where lower(last_name) like '%" + txtSearch.Text.ToLower() + "%'");
                    break;
                case "Company":
                    GetData("select * from BizContacts where lower(COMPANY) like '%" + txtSearch.Text.ToLower() + "%'");
                    break;

            }
        }

        private void BtnExport_Click(object sender, EventArgs e)
        {
            _Application excel = new Microsoft.Office.Interop.Excel.Application();
            _Workbook workbook = excel.Workbooks.Add(Type.Missing);
            _Worksheet worksheet = null;

            try
            {
                worksheet = workbook.ActiveSheet; // set active sheet
                worksheet.Name = "Business Contacts";

                for (int rowIndex = 0; rowIndex < dataGridView1.Rows.Count-1; rowIndex++)
                {
                    for (int colIndex = 0; colIndex < dataGridView1.Columns.Count; colIndex++)
                    {
                        //worksheet.Cells[rowIndex + 1, colIndex + 1] = dataGridView1.Rows[rowIndex].Cells[colIndex].Value.ToString();
                        if (rowIndex == 0)
                        {
                            worksheet.Cells[rowIndex + 1, colIndex + 1] = dataGridView1.Columns[colIndex].HeaderText;
                        }
                        else
                        {
                            worksheet.Cells[rowIndex + 1, colIndex + 1] = dataGridView1.Rows[rowIndex].Cells[colIndex].Value.ToString();
                        }
                    }
                }

                if(saveFileDialog1.ShowDialog() == DialogResult.OK)
                {
                    workbook.SaveAs(saveFileDialog1.FileName);
                    Process.Start("excel.exe", saveFileDialog1.FileName);
                }

            } catch(Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
            finally // clean up
            {
                excel.Quit();
                workbook = null;
                excel = null;
            }
        }
    }
}
